/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HttpListener;

public class App {

    public static void main(String[] args) {

        int port = 8080; // where to listen to
        String wwwroot = "./wwwroot"; // base path of the web content

        try {
            // if present use the first arg as port number
            if (args.length >= 1)
                port = Integer.parseInt(args[0]);

            if (args.length >= 2)
                wwwroot = args[1];

            SimpleHttpListener listener = new SimpleHttpListener(port, wwwroot);
            listener.run();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
}
